class FakeError(Exception):
    def __init__(self):
        super().__init__("Congratulations on finishing all the exercises!")

# This code may not make much sense yet but it's a preview of what we'll be doing in the next few days